# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Download/icf.xdc

# IP: ip/imem/imem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imem || ORIG_REF_NAME==imem} -quiet] -quiet
