# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Harry/university/CPU/Pipeline/Pipeline.cache/wt [current_project]
set_property parent.project_path D:/Harry/university/CPU/Pipeline/Pipeline.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Harry/university/CPU/Pipeline/Pipeline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Harry/Download/fib.coe
add_files D:/Harry/Download/stuno.coe
read_verilog -library xil_defaultlib {
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/Defines.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/ALU.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/Adder4.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/AdderJump.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/AluControl.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/BranchControl.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/BranchForwardingUnit.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/Comparator.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/Control.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/DataMemory.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/EXMEMReg.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/ForwardingUnit.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/HazardDetectionUnit.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/IDEXReg.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/IFIDReg.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/ImmGen.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/InstructionMemory.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/MEMWBReg.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/Mux.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/Mux_4.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/PC.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/Pipeline.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/imports/Download/RegisterFile.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/new/seg7x16.v
  D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/new/Top.v
}
read_ip -quiet D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/ip/imem/imem.xci
set_property used_in_implementation false [get_files -all d:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/ip/imem/imem_ooc.xdc]

read_ip -quiet D:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/ip/blk_mem/blk_mem.xci
set_property used_in_implementation false [get_files -all d:/Harry/university/CPU/Pipeline/Pipeline.srcs/sources_1/ip/blk_mem/blk_mem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Harry/university/CPU/Pipeline/Pipeline.srcs/constrs_1/imports/Download/icf.xdc
set_property used_in_implementation false [get_files D:/Harry/university/CPU/Pipeline/Pipeline.srcs/constrs_1/imports/Download/icf.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
